---

name: Test package

on: [push]

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t bbva2pandas .
      - name: Test with Docker
        run: docker run --rm --entrypoint python bbva2pandas -m unittest discover -s /app/tests -v
